# This is a basic workflow that is manually triggered

name: Manual deployment workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      version:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Version to deploy'
        # Input has to be provided for the workflow to run
        required: true

jobs:
  # This workflow contains a single job called "greet"
  setversion:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Check version that will be deployed
      run: echo "Hello ${{ github.event.inputs.version }}"
      
    # Runs a single command using the runners shell
  deploy:
  needs: setversion
  environment:
      name: staging
      url: ${{ steps.deploy_staging.outputs.webapp-url }}    
    - name: Run command that needs to be approved
      run: echo "Hi! this is sensitive commant that needs approval"
