# This is a basic workflow that is manually triggered

name: Manual deployment workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      version:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Version to deploy'
        # Input has to be provided for the workflow to run
        required: true

jobs:
  # This workflow contains a single job called "greet"
  setversion:
    name: Set version to deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check version that will be deployed
        run: echo "Hello ${{ github.event.inputs.version }}"        
  deployment:
    environment: test
    needs: setversion
    runs-on: ubuntu-latest
    name: Deploy to test stage
    steps:
    - name: Check version that will be deployed
      run: echo "Hello ${{ github.event.inputs.version }}"
